### ISSUE TITLE
issue installing snappy

### ISSUE THREAD

**Issue by jburmistrova** [rodrigo-pena/sentinel-fusion#1]
Hi I'm having an issue installing snappy specifically at the part where I need to install jpy. 

I get the following error:
```
203 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1
```

I see that this has happened to other Catalina users. Was this something you encountered when installing snappy?

**Comment by rodrigo-pena** [comment]
Hi, to me this sounds like the Xcode Command Line Tools are not installed. Try going following the instructions [here](https://www.embarcadero.com/starthere/xe5/mobdevsetup/ios/en/installing_the_commandline_tools.html) to install the command line tools and see if the error persists.

**Comment by jburmistrova** [comment]
I installed Xcode Command Line Tools while trouble shooting this issue, plus I installed gcc using brew install. I still have the same issue with jpy

**Comment by rodrigo-pena** [comment]
Hmm, what does the command `which gcc` show when inside and outside the `sentinel-fusion` conda environment?

Another thing you coul do is first delete the `.whl` files from jpy that you have in the directory `~/.snap/snap-python/snappy/`. Then, try downloading other released versions of wheels from [https://github.com/bcdev/jpy/releases](https://github.com/bcdev/jpy/releases) and see if the snappy installation works then.

**Comment by d1larak1m** [comment]
I also had this problem. You just need to add two lines to the code from the described directory
[link to solution](https://github.com/bcdev/jpy/issues/190)

**Comment by rodrigo-pena** [comment]
Thanks for the solution, @d1larak1m . I'll mark this issue as closed then
